### PR TITLE
Fixed a grammatical error in the README file of the repo.

### PR DESCRIPTION
**Pull request by Ronit-Dutta**
Hi,
I have fixed a grammatical error in the README file of the repo. Please review and approve.
Regards,
Ronit Dutta.

### CODE REVIEW

**Comment by Zircoz** [comment]
Wait, what???? xDxDxDxDxDxDxDxDxD
@aryangulati ya gotta see this.
Btw @Ronit-Dutta the changes you made, don't even work as intended.

**Comment by Ronit-Dutta** [comment]
Bro I just made the word "documentation " right that was written wrong. Why did you find it funny?

**Comment by Zircoz** [comment]
I couldn't scroll down enough; your other changes cracked me up.
I will re-review now when I know the actual change.

**Review by Zircoz — CHANGES_REQUESTED** [review]
fix broken emojis (hint: they were fine earlier)

**Comment by Zircoz** [comment]
When you have made the changes, reopen this PR and request review @Ronit-Dutta

**Pull request closed without merging**
