### PR TITLE
Object Detection project

### PR DESCRIPTION
**Pull request by amansoni24**

### CODE REVIEW

**Comment by amansoni24** [comment]
Hi @aryangulati ,
Please add "hacktoberfest-accepted" label and approve my project
Thank you. :)

**Comment by aryangulati** [comment]
Hey @amansoni24 please add .py file instead of .ipynb file and also if you are adding more than one projects you can make a folder for Object Detection Happy Coding

**Comment by Zircoz** [comment]
Just commenting to get updates.

**Comment by amansoni24** [comment]
> Hey @amansoni24 please add .py file instead of .ipynb file and also if you are adding more than one projects you can make a folder for Object Detection Happy Coding

Hey @aryangulati . I have now added a .py file. Do have a look . Thank You.

**Pull request merged**
